title: OKE with Oracle DevOps Workshop
description: OKE with Oracle DevOps Workshop
schemaVersion: 1.1.0
version: "20190304"


variableGroups:
  - title: "Environment Configuration"
    variables:
      - compartment_id
  - title: "Node Pool Configuration"
    variables:
      - num_pool_workers
      - node_shape
      - node_pool_node_shape_config_ocpus
      - node_pool_node_shape_config_memory_in_gbs
  - title: "Tenancy Information"
    variables:
      - tenancy_ocid
    visible: false

variables:

  compartment_id: 
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create resources"
    required: true

  num_pool_workers:
    type: integer
    title: "Number of Worker Nodes"
    minimum: 1
    maximum: 1000
    required: true
    visible: true

  node_pool_shape:
    type: oci:core:instanceshape:name
    title: "Select a shape for the Worker Nodes instances"
    required: true
    dependsOn:
      compartmentId: compartment_ocid
    visible: true

  node_pool_node_shape_config_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    title: "Number of OCPUs"
    visible:
      and:
        - or:
          - eq:
            - node_pool_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.A1.Flex"

  node_pool_node_shape_config_memory_in_gbs:
    type: integer
    minimum: 1
    maximum: 1024
    title: "Amount of memory (GB)"
    visible:
      and:
        - or:
          - eq:
            - node_pool_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.A1.Flex"
